### ISSUE TITLE
Добавить на типовую файлы для скачивания (icoomon)

### ISSUE THREAD

**Issue by maxouni** [maxouni/angular-start-kit#4]

**Comment by rieset** [comment]
А как именно планируешь делать? Что было бы удобно для работы с иконками?

Подумал, что через npm круто с иконками разбираться. Нашел тулзу.
https://www.npmjs.com/package/icomoon-build

**Comment by rieset** [comment]
Может страницу, на которой все иконки icomoon текущего проекта выводятся.

А с помощью этого, можно автоматически экспортировать набор и импортировать (раскатывать его в проекте)
https://www.npmjs.com/package/icomoon-builder

**Comment by maxouni** [comment]
Пока сделал так https://angular-start-kit.herokuapp.com/guideline

Для страницы иконок и автосборщика icomoon создам issue
